### ISSUE TITLE
Maya Attribute does not exist (or is not unique):: u'world_ctl.hideOnPlayback'

### ISSUE THREAD

**Issue by mottosso** [miquelcampos/mgear#213]
Looks like a new attribute for Maya > 2015, works in Maya 2018.

To reproduce:

1. Import Biped Guide
2. Build From Selection

```python
...
Get parenting for: foot_R0
Get parenting for: legUI_R0
Guide loaded from hierarchy in  [ 0:00:02.078000 ]

= BUILDING RIG ==============================================
Initial Hierarchy
# Error: Maya Attribute does not exist (or is not unique):: u'world_ctl.hideOnPlayback'
# Traceback (most recent call last):
#   File "C:\Program Files\Autodesk\Maya2015\Python\lib\site-packages\pymel\internal\factories.py", line 779, in callback
#     res = origCallback( *newargs )
#   File "C:\mgear\scripts\mGear_guidesTemplates.py", line 16, in buildFromSelection
#     gui.Guide_UI.buildFromSelection()
#   File "C:\mgear\scripts\mgear\maya\shifter\gui.py", line 166, in buildFromSelection
#     rg.buildFromSelection()
#   File "C:\mgear\scripts\mgear\maya\shifter\__init__.py", line 136, in buildFromSelection
#     self.build()
#   File "C:\mgear\scripts\mgear\maya\shifter\__init__.py", line 161, in build
#     self.initialHierarchy()
#   File "C:\mgear\scripts\mgear\maya\shifter\__init__.py", line 280, in initialHierarchy
#     self.global_ctl.attr("hideOnPlayback"))
#   File "C:\Program Files\Autodesk\Maya2015\Python\lib\site-packages\pymel\core\nodetypes.py", line 1470, in attr
#     raise e
# MayaAttributeError: Maya Attribute does not exist (or is not unique):: u'world_ctl.hideOnPlayback' # 
```

**Comment by miquelcampos** [comment]
@mottosso  I have fixed this issue. Please check if is working for you. Thanks
