### ISSUE TITLE
Rigbits: ChannelWrangler: Doesn't work in Maya 2018.1

### ISSUE THREAD

**Issue by miquelcampos** [miquelcampos/mgear#90]
Same code works in Maya 2017

```
// Error: super(type, obj): obj must be an instance or subtype of type
# Traceback (most recent call last):
#   File "C:\Program Files\Autodesk\Maya2018\Python\lib\site-packages\pymel\internal\factories.py", line 785, in callback
#     res = origCallback(*newargs)
#   File "D:\repo\mgear\release\scripts\mgear\maya\rigbits\channelWrangler.py", line 422, in openChannelWrangler
#     gqt.showDialog(channelWrangler)
#   File "D:\repo\mgear\release\scripts\mgear\maya\pyqt.py", line 85, in showDialog
#     windw = dialog(maya_main_window())
#   File "D:\repo\mgear\release\scripts\mgear\maya\rigbits\channelWrangler.py", line 96, in __init__
#     self.cwUIInst = cwUI()
#   File "D:\repo\mgear\release\scripts\mgear\maya\rigbits\channelWrangler.py", line 86, in __init__
#     self.setupUi(self)
#   File "D:\repo\mgear\release\scripts\mgear\maya\rigbits\channelWranglerUI.py", line 42, in setupUi
#     self.channelMapping_tableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
#   File "D:\repo\mgear\release\scripts\mgear\maya\rigbits\widgets.py", line 46, in __init__
# TypeError: super(type, obj): obj must be an instance or subtype of type //
```

**Comment by miquelcampos** [comment]
Looks like the error was caused by bad re-import
